# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# The name of your site. Is used throughout the theme in places like the site masthead and <title> tags.
title: "Shuaishuai's Webpage"
# A short tagline that appears below the title in site masthead.
subtitle: "Broaden knowledge. Seek truth. Develop virtue."
# Don't want to include email for now
# email: your-email@example.com
description: "Shuaishuai's personal webpage."
# https://github.com/ShuaishuaiYuan/ShuaishuaiYuan.github.io
repository: "ShuaishuaiYuan/ShuaishuaiYuan.github.io"
# The subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://ShuaishuaiYuan.github.io"

# https://github.com/mmistakes/minimal-mistakes#installation
# Only the remote theme is GitHub Pages compatible, the gem-based theme is not.
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

#
# More Site Settings
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/
# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
#
# Other options are:
# "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "aqua"
# To enable site-wide search
search: true
# Used as the defaults for defining what appears in the author sidebar.
author:
  name: "Shuaishuai Yuan"
  avatar: "/assets/images/bio-photo2.jpg"
  bio: "An explorer in the atomic world of materials. " # Note: change to "A designer of the electronic structures of materials." in the future
  location: "Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ShuaishuaiYuan"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.ca/citations?user=VV2o-ysAAAAJ&hl=en"

# The most important is `jekyll-include-cache`, otherwise, github pages won't built
# even though it works locally.
# https://github.com/mmistakes/minimal-mistakes/issues/1875
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Reading Files
include:
  - .htaccess
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - readme.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # https://mmistakes.github.io/minimal-mistakes/docs/posts/
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
